### ISSUE TITLE
玩起来太坐牢了

### ISSUE THREAD

**Issue by chenxing61** [QbdqmQ/Enlightenment#1]
开的快速，然后就是每一回合工人翻个几页，ai工人到处乱跑，科技比政策高几个时代，伟人买几个就高价了，节奏异常地慢。。。
建议：
1.工人要么改回原来文明5的机制，要么加一移动力也行，总之太坐牢了，每回合都要花一堆精力微操。就连修路都要安排，用不完还要找地方放，还特别容易拿错。
2.增加一些科技树和政策点数之间的联系，上手感觉政策点数和科技严重脱线，最好能添加另外一些早期获取政治点数的途径，或者正常获取政治家，让政治家能在普通城市地块里面工作等。或者还可以适当降低政策花费。
3.修下ai？一天到晚工人到处乱窜被蛮人俘虏，刷好感刷爆了。
4.修专业区域产出比市中心建筑低太多，没什么修的价值，除了没有维护费之外没什么优点，建议加强区域。
5.除以上问题之外，这mod在安排新机制上算数一数二了，感觉新系统只是欠磨合，实际上非常有潜力和可玩性，如果要英文翻译可以找我，我愿意帮忙。

**Comment by chenxing61** [comment]
对了，资源工人还没办法平地起农场

**Comment by QbdqmQ** [comment]
> 对了，资源工人还没办法平地起农场

这是特意设置的

**Comment by QbdqmQ** [comment]
> 开的快速，然后就是每一回合工人翻个几页，ai工人到处乱跑，科技比政策高几个时代，伟人买几个就高价了，节奏异常地慢。。。 建议： 1.工人要么改回原来文明5的机制，要么加一移动力也行，总之太坐牢了，每回合都要花一堆精力微操。就连修路都要安排，用不完还要找地方放，还特别容易拿错。 2.增加一些科技树和政策点数之间的联系，上手感觉政策点数和科技严重脱线，最好能添加另外一些早期获取政治点数的途径，或者正常获取政治家，让政治家能在普通城市地块里面工作等。或者还可以适当降低政策花费。 3.修下ai？一天到晚工人到处乱窜被蛮人俘虏，刷好感刷爆了。 4.修专业区域产出比市中心建筑低太多，没什么修的价值，除了没有维护费之外没什么优点，建议加强区域。 5.除以上问题之外，这mod在安排新机制上算数一数二了，感觉新系统只是欠磨合，实际上非常有潜力和可玩性，如果要英文翻译可以找我，我愿意帮忙。

1.工人现在加强了
2.现在政策改了触发条件
3.ai现在加强了很多
4.区域效果我设计是给予城市区域产出的，但是看起来效果不好，我暂时没有好的主意
5.感谢您的游玩，可以帮修缮一些英文翻译吗？我的英文翻译很多都是用DeepL来翻译的
